package com.quickpm

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
	
    def filters = {
		assets(uri:"/assets/**") {
			 before = {
				 // Don't authenticate
				 return true
			 }
		 }
        others(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName || controllerName == 'assets') return true

                // Access control by convention.
                accessControl()
            }
        }

    }
}
